name: NCTL Scan Dockerfile in docker Demo
run-name: ${{ github.actor }} has triggered Scan Action 🚀
on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  NCTL-Scan-Dockerfile-in-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      
    - name: Download and Install nctl
      shell: bash
      run: |
        #!/bin/bash

        shopt -s expand_aliases
        set -e
        # Determine the download URL based on the release version

        curl -L -o nctl.zip "https://nirmata-downloads.s3.us-east-2.amazonaws.com/nctl/nctl_4.0.1/nctl_4.0.1_linux_amd64.zip"
        ls -lrt
        unzip -o nctl.zip
        ls -lrt
        chmod +x nctl

    - name: Check nctl version
      run: |
        ./nctl version
        ./nctl login --url https://nirmata.io --userid dolis@nirmata.com --token 87s9aymmWxG1c8q9min2caU6M4X9kmDtXQNc+LFQHLLCVhsW6QzHawQ2pQKZr5e3xc4zgTm+9cU3tl1v+d5WbA==

    - name: Run the Docker command
      run: ./nctl scan repository --policies ./policy/
    
    - run: echo "🍏 This job's status is ${{ job.status }}."
